### ISSUE TITLE
No message to warn against library imports

### ISSUE THREAD

**Issue by UK-7** [google/tie#100]
Reproduction Steps:
1. Open "app.html"

2. Navigate to a question

3. Add a library import like `import string` or `import re`

4. Use the import in the function like `word[0] in string.whitespace` or `re.compile(r'\w')`

5. Click Run

Current message is:
`NameError: name 'string' is not defined on line 3 `

Which could be:
`Library imports are not permitted for this problem`

![screen shot 2017-04-04 at 10 15 23 am](https://cloud.githubusercontent.com/assets/3907413/24669922/f897774e-1920-11e7-8e58-49bdd82567a2.png)

Standard library imports like re and string may not be allowed as they make the problem solution too simple and unchallenging. However, it might be a god idea to say that explicitly.

[EDIT Mar 4, 11:24]
Suggested Solutions:
**Option 1: Ban the use all libraries for all questions**
This is a blanket solution. For each solution to any problem, check for an import statement. If there is one, don't compile the problem. Instead, show a message saying imports are not permitted.
This is how the system is currently designed and would only require adding a check and a message. This can be a good minimal solution.

**Option 2: Ban libraries specific to questions**
We could have two sets of libraries - banned in every question e.g. `pandas` and banned for this specific question e.g. `re` for string manipulation questions. This is a more elegant and sustainable solution and requires a little more work than the first option

**Comment by eyurko** [comment]
For this issue we'll definitely want to have clear reproduction steps and maybe screenshots. You've already gotten expected/observed behavior, so thank you for that.

What do you think the best way to go about implementing this could be?

**Comment by eyurko** [comment]
This also seems similar to #87.

**Comment by lumig242** [comment]
But import is allowed inside a function call. 

![image](https://cloud.githubusercontent.com/assets/4253578/24672882/1c1d3de8-192b-11e7-8dab-1380c79af53f.png)

I'd suggest making the use of standard library like re/string/collections legal cause these are part of the python language. But for third-party tools including numpy/pandas etc. , they are not suitable for an OJ system.

**Comment by UK-7** [comment]
I didn't try adding the imports within the function definition, only like a regular python file. Perhaps we can add a message making that more clear.

I agree that standard library functions should mostly be available, but in some cases they might make the solution to a problem too trivial. I guess the objective is not to get the problem solution to but encourage thinking towards non-obvious solutions.

**Comment by seanlip** [comment]
Leaving this one open, since it has more detail. I closed #87.
