### ISSUE TITLE
Strange characters after pressing ctrl+z

### ISSUE THREAD

**Issue by cwcai633** [google/tie#104]
How to reproduce:

1. Open app.html with Chrome in Ubuntu 14.04;
2. In question 1, select the text box where to enter the code;
3. Without typing anything, press ctrl+z (the shortcut to rescind some edit), one could get what shows in the screenshot.

![screenshot from 2017-04-04 10 42 19](https://cloud.githubusercontent.com/assets/5900958/24670617/9b86f522-1923-11e7-8525-1f7d6a0902b5.png)

**Comment by luofei11** [comment]
This seems to be the same with #92.

**Comment by seanlip** [comment]
Closing as duplicate.
