### ISSUE TITLE
Horizontal scrolling in editor leads to UI issue

### ISSUE THREAD

**Issue by abinash-behera** [google/tie#108]
**Reproduction Steps:**

1. Open the app.html file in chrome
2. Go to Sample Question 1 (Any sample question would do)
3. Add a long line of code that extends beyond the visible area
4. Scroll to the extreme right using the horizontal scroll bar

**Expected Output:** The line numbers should not overlap with the code 

**Actual Output:** The code contents overlap with the line numbers on the left
![screenshot from 2017-04-04 11 44 53](https://cloud.githubusercontent.com/assets/15383817/24673172/33f80e7e-192c-11e7-9344-78fda2fbb107.png)

**Comment by eyurko** [comment]
Might be worth playing around with some of the information here: https://codemirror.net/doc/manual.html

**Comment by abinash-behera** [comment]
Fixed by PR [132](https://github.com/google/tie/pull/132).
