### ISSUE TITLE
User can change size of text boxes

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#112]
### Behaviour
![screenshot from 2017-04-04 13 29 47](https://cloud.githubusercontent.com/assets/1597618/24677199/ce265b32-193a-11e7-8927-27e0344bd7a1.png)

The text areas with the instruction and the question can be resized by the user.

### Expected behaviour
Text areas resize or become scrollable based on the amount of text in them (with a fixed minimum size)

### Repro steps
1. Open app.html
2. Click and drag from the marker on the bottom right corner of the instuction/question box

**Comment by eyurko** [comment]
If this is something we want to fix, this looks like a good place to look: http://stackoverflow.com/questions/5235142/how-to-disable-resizable-property-of-textarea

**Comment by shaman-rajan** [comment]
Shall I create a PR to fix?

**Comment by seanlip** [comment]
Yes, please go ahead.

**Comment by seanlip** [comment]
That said, could you please ask 3-5 people and see whether the resize behavior is desirable or not before doing so? Thanks!

**Comment by seanlip** [comment]
@shaman-rajan -- did you get feedback on this?

**Comment by shaman-rajan** [comment]
I did, and most people are okay with it being there - no strong preference either way. Almost everyone requested for the editor box to be resizeable, so maybe we close this issue and open up a new one for that?

**Comment by seanlip** [comment]
Sounds good! Thanks @shaman-rajan.
