### ISSUE TITLE
Element width not consistent and no centering in smaller window size

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#113]
### Behaviour
On a larger window, everything is centered with the same height on the left and right sides:
![screenshot from 2017-04-04 13 40 46](https://cloud.githubusercontent.com/assets/1597618/24677644/56604002-193c-11e7-9f54-8d4ef6979284.png)

On smaller windows, the elements do not have a consistent width, nor are they centered on the page. Also, the extra height on these is not required when the elements are stacked vertically.
![screenshot from 2017-04-04 13 43 15](https://cloud.githubusercontent.com/assets/1597618/24677731/ad61ab98-193c-11e7-92aa-c29bde15e9a1.png)

### Repro steps
1. Open app.html
2. Decrease browser window size till the question box goes below the code editing box

**Comment by shaman-rajan** [comment]
Might be fixed by #200 . Will get back to it after PR is merged.

**Comment by seanlip** [comment]
Is this fixed?

**Comment by seanlip** [comment]
(or, rather, obsolete?)

**Comment by seanlip** [comment]
Note: this was closed because it is now obsolete.
