### ISSUE TITLE
Allow students to ask questions.

### ISSUE THREAD

**Issue by seanlip** [google/tie#125]
(This comes from a suggestion in #88.)

It would be nice to have some sort of way for students to "ask questions". This could be as simple as having a question mark button in the bottom right and allowing them to select, multiple-choice style, clarifying questions from it (including "can I have a hint, please?"). That way, although they might not be able to practice coming up with questions on their own, at least they get a feel for what sort of thing to ask.

**Comment by xiaoyig** [comment]
It will also be nice to create some kind of discussion board for students to share their thoughts of how to improve performance of certain questions or make suggestions for other people's ideas.

**Comment by BenjaminHolland** [comment]
You could ask participants to submit a "Question To Ask" when they solve each task. Other students could then "Request a question to ask" to help them think about the problem in ways they might not have thought of themselves, without directly giving away the answers.

**Comment by rabidbit** [comment]
Per offline discussion, rejecting / closing this idea for now.
