### ISSUE TITLE
Add functionality for e2e tests to ensure that the application does not break.

### ISSUE THREAD

**Issue by seanlip** [google/tie#126]
We should probably add an end-to-end test that loads the page and clicks some of the buttons / submits some code, in order to prevent breakages like the one that was fixed in #80. (Note that even an end-to-end test which just loads the app.html page in a browser and checks that there are no console errors would have helped here.)

Protractor is likely to be a good library for this, and is worth investigating.

**Comment by luofei11** [comment]
working on this...
