### ISSUE TITLE
Implement inputFunctionName feature for correctnessTest and buggyOutputTest

### ISSUE THREAD

**Issue by eprym** [google/tie#144]
We are creating the question of  "find closest value in binary search tree", and we need to use the inputFunctionName feature to transform string to BST, and it hasn't been implemented. So we are working on it.

**Comment by Eumenides2009** [comment]
we found that performanceTest does not take inputFunctionName parameter in data schema, so we will not  change this one.

**Comment by seanlip** [comment]
Fixed in #185. Thanks @eprym and @Eumenides2009 !
