### ISSUE TITLE
Write a Karma test to ensure that "infinite recursion" code times out gracefully.

### ISSUE THREAD

**Issue by seanlip** [google/tie#156]
We should add a Karma test to ensure that the timeout case is handled correctly. It should check that, if the user types code that effectively runs forever, the evaluation should complete and its result should be "timeout error".

/cc @eyurko

**Comment by eyurko** [comment]
CAVEAT: make sure to sync in karma.conf.js

   'third_party/skulpt-c14015/skulpt.min.js',
   'third_party/skulpt-c14015/skulpt-stdlib.js',

**Comment by seanlip** [comment]
Fixed in #289. Thanks @eyurko!
