### ISSUE TITLE
Give graduated feedback for syntax errors.

### ISSUE THREAD

**Issue by seanlip** [google/tie#157]
In an interview setting, students are not going to get feedback that a syntax error has happened "on line X, column Y". To be fair, such syntax errors probably don't matter too much anyway. However, in TIE, the code has to be syntactically correct so that it can run and so that feedback can be given.

A possible middle ground might therefore be to do the following: when a syntax error is found, highlight the line that contains it in red, and say something along the lines of "there's a syntax error here; please find it and fix it", while offering an optional popup hint that shows the exact error and line number. That way, if a student wants to practice finding syntax errors on inspection, they have the opportunity to do so; if they don't want to practice this, they can just open the popup.

**Comment by luofei11** [comment]
A few questions:
1. Why do we need to highlight the line, instead of letting students find the syntax error by themselves?
2. Is there a specific reason to use a popup?

**Comment by seanlip** [comment]
For (1), we could do either. It might be worth getting some informal feedback on this; what I proposed was just a suggestion.

For (2), no; it's one way, but there may be others. The main thing was that I wanted the student to be in control of deciding whether to take the hint or not.

**Comment by luofei11** [comment]
Current design and implementation as follows:
1. Initial view
![before_run](https://cloud.githubusercontent.com/assets/5546251/25056812/2abd7dca-2120-11e7-9dd3-2bba3ad09b85.png)
2. Run the code with syntax error
![after_run](https://cloud.githubusercontent.com/assets/5546251/25056823/399827fa-2120-11e7-93da-178c0719ee35.png)
3. take hint
![hint](https://cloud.githubusercontent.com/assets/5546251/25056832/41845b1e-2120-11e7-8689-06492b5aad5f.png)
4. hide hint
![hide](https://cloud.githubusercontent.com/assets/5546251/25056842/48cab8c8-2120-11e7-8f75-1bf2d75b75f9.png)

No CSS is applied on the button now. I talked with others and it seems acceptable. Any comments? @seanlip @rabidbit

**Comment by seanlip** [comment]
The functionality seems fine to me, except that I'm not sure why you'd want to hide the hint after showing it. Deferring to @rabidbit for design review.

**Comment by rabidbit** [comment]
Some feedback:
1. Change the the button to a link with small font ("Display error details" / "Hide error details"); we want to use buttons very sparingly and try to avoid embedding buttons into the text windows. Append the link inline after the "Try to find and fix it." sentence (as opposed to a new line).
2. Hide the error messages by default, but once the user toggles it one way or the other, hide or unhide all error message details (so the user won't have to click on links every single time there is an error to display details).

**Comment by luofei11** [comment]
I agree with the first one, but for the second, imagine this scenario:
There might be several syntax errors at different lines. Our functionality can only show the first syntax error it met.
The student wants to practice checking for syntax error, but didn't manage to find it. So he or she will click for error details. Then he or she fixed the first syntax error following the error detail, and run the code again(he/she will assume there are no other syntax errors). The result is that those other errors will be displayed after the run, even though the student doesn't want to look at them. Am I correct?

**Comment by rabidbit** [comment]
I think I understand what you mean, and I thought about that. My guess is that the user will see the error messages when they didn't want to, maybe 1-3 times. Then, they will learn that they need to click "Hide error details" when they are done looking at an error message if they don't want to see error details going forward. This would be mildly annoying. If, however, the user has to click to see error details for every single error, then they are forced to click multiple times, whether they like it or not. I suspect this might be more annoying because you may be forced to click on links many times (versus remembering to click a few times). Does that make sense?

**Comment by luofei11** [comment]
Yes I admit that it must be more annoying for the user to click many times, but that fits more to an interview setting, doesn't it? Also, my assumption is that users usually won't have a large number of syntax errors, so they might don't need to worry about "too many" clicks.

**Comment by rabidbit** [comment]
That's a good point. Though I would not assume users won't have a large number of syntax errors. I've had interviews where the candidate came up with a solid implementation but wrote with a ton of syntax errors. Also, right now we only have Python, and not everyone is familiar with Python; so, I can see where hiding syntax errors might not be that useful when the user cares more about solving the problem than getting the syntax right. In short, I can see where users will run across a lot of errors, which increases the odds of many clicks. Ultimately, things like this will have to be user-tested, but this is my thinking for the initial approach.
