### ISSUE TITLE
Harden the question verification tests.

### ISSUE THREAD

**Issue by seanlip** [google/tie#158]
In [QuestionSchemaValidationService](https://github.com/google/tie/blob/0580cd73546a9ea77113839b0b84bff5fd1e473f/assets/tests/QuestionSchemaValidationService.js#L21), there are a number of TODOs that involve additional verification (though I think the first of this has been involved in #142 -- @eyurko, is this right?)

The last of these TODOs (verify that the starter code matches a language pattern for the language specified) is probably not worth doing, but I think we should:

- [x] Verify that AuxiliaryCode contains the AuxiliaryCode class definition.
- [x] Verify that starter code contains the necessary Python function definitions.

since these should be reasonably straightforward tests to write.

**Comment by lumig242** [comment]
@seanlip @eyurko 

Some of the TODOs are already implemented in 'TaskSchemaValidationService.js'.

1. // TODO(sll): Verify that the BuggyOutputTest messages are unique across
    // all tasks.
https://github.com/google/tie/blob/0580cd73546a9ea77113839b0b84bff5fd1e473f/assets/tests/TaskSchemaValidationService.js#L162

2. // TODO(sll): Verify that starter code contains Python function definitionshttps://github.com/google/tie/blob/0580cd73546a9ea77113839b0b84bff5fd1e473f/assets/tests/TaskSchemaValidationService.js#L53

**Comment by lumig242** [comment]
"Verify that AuxiliaryCode contains the AuxiliaryCode class definition." is in #217

**Comment by lumig242** [comment]
#217 has been merged. @eyurko Could you please take a look if we can close this issue?
