### ISSUE TITLE
Doesn't support list of strings as allowedOutPuts

### ISSUE THREAD

**Issue by skywalker-lili** [google/tie#167]
In the questions js files, if set the `allowedOutputs` of `correctnessTests` to a list of strings, then even if the learner's function return the correct list of strings, it is still judged as wrong answer.

Reproduce procedure:
Here, I modify the default parens.js file to reproduce this issue.
1. Open /assets/questions/parens.js file; locate to `allowedOutPuts` variable in the 1st test case for the 1st task (`tasks` -> `correctnessTests`-> `allowedOutPuts`, around line 62 if this file doesn't change)
2. Change the original `[True]` to `[["1", "2"]]` so that the correct output is a list of two strings.
3. Use browser to open /client/app.html. In the page opened, click the icon 2 for the 2nd problem, which is the question that we just modified.
4. In the learner's coding zone, set the function `isBalanced(s)` to `return ["1", "2"]`, so the return matches the `allowedOutPuts`.
5. click run button in the page, which then shows the code fails this test case.

Expected: since we hard-code the answer to be the same as the `allowedOutPuts` in the question file, the code should pass this test case.

Screenshot:
![parens_issue_not_accepting_list_of_strings](https://cloud.githubusercontent.com/assets/5773915/24769631/03d765d2-1abc-11e7-884d-6d1f13d96f95.png)

**Comment by seanlip** [comment]
Fixed in #183. Thanks @skywalker-lili!
