### ISSUE TITLE
Give users positive reinforcement about anticipating edge cases and feedback on failing tests

### ISSUE THREAD

**Issue by apicardgoog** [google/tie#186]
When a user's code passes a broad category of tests (e.g. short inputs) we would like to give positive reinforcement for their work.
Also, if tests that used to pass stop working, we would like to remind them that their code needs to be fixed.

We would like to do this by adding tags to the test inputs that group them into relevant categories (e.g. "the general case", "short inputs", "large inputs", "sorted inputs", etc.). 

Then, all inputs would need to be evaluated with each run in order to determine the tags that are passing and the tags that are still failing.

Design doc is here:
https://goto.google.com/tie-positive

Suggested implementation:
1. Maintain a list of tags whose tests are all passing (passing_tags_list starts off empty) and a list of failing tests that are displayed in the output (displayed_failing_tests_list starts off empty)
2. Run all the tests compiling a list of all passing tests and a separate list of all failing tests.
3. If all the tests with a particular tag are passing and that tag is not in passing_tags_list, add "☑ Handles <name of tag>" to the output and add the tag to the list.
4. If a test fails that is associated with a tag in passing_tags_list, change the check mark to a red X for the entry that refers to the tag name. Add the test to displayed_failing_tests_list and display a message of the form "☒ Fails on 'abc'".
5. If a test in  displayed_failing_tests_list goes back to passing, update the X to a check mark. Evaluate whether the check mark next to corresponding tag message should become a checkmark too (depends on whether other tests with that tag are still failing)
6. Optional, if no formerly passing test has started failing, prompt the user about the next failing test.

**Comment by seanlip** [comment]
Fixed in #251. Thanks @shaman-rajan!
