### ISSUE TITLE
Question Title UI Modifications for better space utilization and prominence

### ISSUE THREAD

**Issue by abinash-behera** [google/tie#189]
**Description:** Every question title has a prefix "Question #:" in it. This is redundant as the question index is already being displayed in the navigation bar on the top. The highlighted index number displays the current question number. So, we can remove the "Question #:" prefix from the question title. 
Also, the CSS of the question title can be modified to make it more prominent.

**Current state:** 
<img width="1343" alt="screen shot 2017-04-10 at 10 37 54 am" src="https://cloud.githubusercontent.com/assets/15383817/24874548/e5e3dfee-1dd9-11e7-8fbd-f5ea96e4646d.png">

**Suggested Modification:** The following screenshot is just a mock-up of the suggested modifications.We can have a discussion about the best way to approach the same. 
<img width="1354" alt="screen shot 2017-04-07 at 10 25 59 am" src="https://cloud.githubusercontent.com/assets/15383817/24873848/4918f228-1dd7-11e7-89d5-531589e98759.png">

**Comment by seanlip** [comment]
Hi @rabidbit -- any thoughts on this?

**Comment by rabidbit** [comment]
I think removing the number is fine. I think the color and alignment could be tweaked, but I know this is just a quick mock-up. I don't think the question title needs to be too prominent (otherwise, it distracts the eye).

**Comment by seanlip** [comment]
Sounds good, thanks! @abinash-behera -- you might also want to get some informal feedback from others when developing this, so that you can iterate towards a good design.
