### ISSUE TITLE
Make auto-save responsive to use interaction

### ISSUE THREAD

**Issue by rabidbit** [google/tie#213]
#209 implements auto-save but it simply runs auto-save every 30seconds and is not based on user interactions.

Rather than saving every 30seconds (or any other static interval), auto-save should be activated 3 seconds after an edit event with saves set 8 seconds apart (that is "Saving code..." displayed for 3 seconds, then 5 second pause, then auto-save again). That is, if the user makes a quick change, it auto-saves after 3 seconds. If the user keeps typing non-stop for while, it saves every 8 seconds while the user types until the user finishes typing (it saves one last time 8 seconds after the user finishes typing the long code). If the user does not change anything, auto-save is not activated.

**Comment by wmcalyj** [comment]
@rabidbit I am not sure if this is a reasonable question but how do I define "quick change" meaning, how to distinguish a "quick change" and a "non-stop change".
Thanks in advance.

**Comment by rabidbit** [comment]
That's a good question. BTW, I just tried this, and I think the timing could be shorter for a user responsive version proposed here (1 second text display rather than 3 seconds, since the frequency can be much higher); so, making adjustments for this, I would suggest the following...

User starts typing... If user stops typing, wait 3 seconds to see if they continue typing. If they don't continue typing, auto-save. If they start to type again before the 3 seconds are up, then start saving every 6 seconds (1 second used to display text + 5 seconds) until the user stops typing for 3 seconds, at which point you auto save. Basically, if the user ever stops typing for 3 seconds, auto-save, but if the user keeps typing with less than 3 second pauses auto-save at 6 second intervals until they pause for 3 seconds (at which point you auto-save).

**Comment by wmcalyj** [comment]
Thank you very much for the detailed explanation John. I will start working on this feature. I might come with lots of questions. Please bare with me. Thanks in advance.

**Comment by rabidbit** [comment]
No worries! Thanks wmcalyj!
