### ISSUE TITLE
Add tests in client/services

### ISSUE THREAD

**Issue by lumig242** [google/tie#223]
- [x] FeedbackGeneratorService.js

- [x] QuestionDataService.js

- [ ] SolutionHandlerService.js (Unable to work on this now)

**Comment by lumig242** [comment]
#219 for FeedbackGeneratorService.js

**Comment by seanlip** [comment]
Quick question: what is the issue with SolutionHandlerService.js?

**Comment by lumig242** [comment]
@seanlip Basically we failed to figure out how to use the `skulpt` library in unit tests. So we were not able to test the functions depending on this.

**Comment by seanlip** [comment]
Ah, ok -- thanks for letting me know! I'll investigate, and move the remaining tests to a new issue.

**Comment by seanlip** [comment]
Superseded by #252, closing. Thanks @lumig242!

**Comment by seanlip** [comment]
Btw @lumig242, in case you're interested, I think @xchenan and @spwahaha actually figured out the Skulpt issue. The version of Skulpt that was being used in karma.conf.js was wrong. See their change here: https://github.com/google/tie/pull/173/files#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfbR15 -- I think that would have fixed the Skulpt tests.

**Comment by lumig242** [comment]
Oh I see. Looks like we were on the wrong track for this problem, unfortunately:(. Thanks @seanlip
