### ISSUE TITLE
Error messages are not interpolated.

### ISSUE THREAD

**Issue by seanlip** [google/tie#25]
Repro instructions: Go to the reverseWords problem, and type the code seen in the screenshot below.

In the screenshot below, the feedback message is not interpolated, so it is meaningless. We should either support interpolation or choose a different feedback message.

![screenshot from 2017-03-01 15 41 42](https://cloud.githubusercontent.com/assets/10575562/23486620/0c5bdf2c-fe96-11e6-8409-ecfa63f240af.png)

**Comment by eyurko** [comment]
Fixed in PR 35.
