### ISSUE TITLE
Confusing text in instructions for findAlphabet question

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#253]
https://github.com/google/tie/blob/master/assets/questions/findAlphabet.js#L232

The word 'frequency' on this line and 'return them in alphabetical order' are both confusing. The first one is not related to the question, and the second might confuse the user as to which alphabetical ordering we are asking for. 

It might make more sense to change the sentence to something like "In case there is not enough information to order multiple characters, return them in the conventional alphabetical order".

**Comment by seanlip** [comment]
Fixed in #254, thanks @eyurko!
