### ISSUE TITLE
Error when running code for isPalindrome question

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#261]
There is an internal error when running any code for the isPalindrome question.
![screen shot 2017-04-26 at 10 48 51 am](https://cloud.githubusercontent.com/assets/1597618/25448702/301c8c96-2a6e-11e7-9fad-afd6c80f931b.png)

**Repro steps:**
1. Open app.html
2. Navigate to question 3
3. Click run

**Comment by eyurko** [comment]
oh that's fun.

**Comment by eyurko** [comment]
Fixed in #266.
