### ISSUE TITLE
time.time used in performance tests.

### ISSUE THREAD

**Issue by BenjaminHolland** [google/tie#271]
This is the most general method, but also probably the least accurate choice for the purposes of testing algorithm performance, which may account for some of the wonkyness of the performance tests.  

time.perf_counter would seem to be the most appropriate choice, being the highest available resolution and being meant for short duration timing rather than long running or user-facing clocks.  However, this is only available in python 3. (I haven't quite figured out which python version we're using yet.)

if we're using 2.7, time.clock may be a better option, as it seems to have better resolution. Apparently this is the function used to analyze python library algos. 

https://docs.python.org/2.7/library/time.html
https://docs.python.org/3.6/library/time.html

**Comment by BenjaminHolland** [comment]
Attaching additional reference material regarding the specific implementation used in Skulpt. Confirms that the implementation of clock and time are different, and that the resolution of time is less than that of clock.

https://github.com/skulpt/skulpt/blob/master/src/lib/time.js

**Comment by seanlip** [comment]
Fixed in #272. Thanks @BenjaminHolland!

(Btw, if you start the PR comment with "Fix #issuenum: ...", GitHub will auto-close the issue when the PR is merged. Just fyi!)
