### ISSUE TITLE
Feedback state lost when switching between windows or reload

### ISSUE THREAD

**Issue by rabidbit** [google/tie#273]
Expected behavior: When switching between questions, feedback state is maintained. Since code is saved, it would be odd to be able to get back to where you left off in terms of your written code but not be able to get back to where you were in terms of the feedback.

Observed behavior: Switching between questions or reloading the page causes the app to lose state on the feedback window.

Steps to reproduce: Modify and run code. Observe feedback. Reload page or go to another question and back again. Observe that feedback is reset.

**Comment by theresa-lee** [comment]
Ah, okay, I thought maybe people would want the feedback to be cleared but it makes sense to save the code + feedback.
