### ISSUE TITLE
Syntax errors only display the last error

### ISSUE THREAD

**Issue by rabidbit** [google/tie#274]
Expected behavior: when running into multiple syntax errors, all past errors can be viewed. This is important for the alternative UI (#268), which maintains a history of feedback.

Observed behavior: In alternative UI, past syntax error feedback is displayed, but only the most recent error message can be viewed.

Steps to reproduce: In alternative UI (#268), generate multiple syntax errors and try to view all the errors. Notice only details of the last error is displayed.

**Comment by seanlip** [comment]
I'm not quite sure I see the point of seeing syntax errors for past code submissions. Why would that be useful to the student? Often these are just due to typos...

**Comment by rabidbit** [comment]
This might be a personal preference thing. I would like to see what kind of errors I hit in the past; so, I would actually find it useful, but I can also see how a long line of syntax errors might not be desirable. I think making consecutive syntax errors collapsed by default (but expandable) might help. 

That is, rather than:

feedback
syntax error 1
syntax error 2
syntax error 3
syntax error 4
other feedback
syntax error 5
syntax error 6
other feedback

Do something like this:

feedback
(4) syntax error
other feedback
(2) syntax error
other feedback

User can expand and view errors as desired.

**Comment by seanlip** [comment]
Yep, that could work. We might want to ask around.

Also, just wondering (out of curiosity): why would you like to see what kind of errors you hit in the past, and why would that be useful?

**Comment by rabidbit** [comment]
Agreed, this is a good example of something to do some user validation/test.

For me, I tend to ask things like, "Didn't I see this error before?" or "Wait, I thought I fixed this.. did I not get this error before?" or "What was that error that I bypassed before? I changed my code to get around it, but I want to look into that error more and learn more about it." There's probably other reasons I want to look back on what happened in the past. As a learner, I am guessing it's more important. As an experienced coder, it might be less important.

This is a good reminder for me to write that "whiteboard mode" spec doc I promised to write. I think not having history is one of the attributes of whiteboard mode.

**Comment by theresa-lee** [comment]
I didn't ask this earlier, but is there a reason why we're hiding the error details? I feel like if I have a syntax error, it would be useful to see where my syntax error is. Especially since we decided to go the route of having all the previous errors showing, would it make more sense to have all of them showing than hidden?
