### ISSUE TITLE
ReverseWords Starter Code Hides str() Builtin

### ISSUE THREAD

**Issue by BenjaminHolland** [google/tie#277]
The name str is a built in python function, but cannot be used in the reverse word challenge because it is hidden by the function argument.

**Comment by BenjaminHolland** [comment]
Ready For Pull pending #272 
BenjaminHolland/tie@51af146969f5798f73c9554c51c7d7f5361d2e87

**Comment by seanlip** [comment]
Btw -- I don't think this PR should be gating on the other PR. You can have multiple PRs open at once, each corresponding to a different branch. Just make sure to checkout the new branch from the latest version of master at the start (i.e., checkout master, do a git pull/fetch to sync things up with the remote, then checkout a new branch, make your changes on that, and push). You can switch between branches using `git checkout branch-name`.
