### ISSUE TITLE
Reset Code button resets feedback window

### ISSUE THREAD

**Issue by rabidbit** [google/tie#279]
Expected behavior: When resetting code, only the code is reset. There should be a separate button to reset feedback (it's possible the user wants to reset one but not the other).

Observed behavior: Reset Code button resets both the code and the feedback window.

Steps to reproduce: Click reset code and note that feedback window is also reset.

**Comment by seanlip** [comment]
I think I would actually be surprised if the feedback didn't reset. I would expect a "reset" action to clear everything, and the feedback at any given time to match the code I've written.

Perhaps we should get more input on this?

**Comment by rabidbit** [comment]
The button says "Reset Code"; if it does more than reset the code, I would be surprised as a user. A "Reset Question" or "Clear Feedback" button would be appropriate for clearing everything or just the feedback respectively. I'd go with "Reset Question" button, which would be in addition to the "Reset Code" button. User study can determine if we need to retain the "Reset Code" button or remove it in favor of "Reset Question" (i.e., determine how useful it is to reset just the code).

**Comment by seanlip** [comment]
Hm, I'm a bit wary of adding yet another button. We have four buttons and dropdowns already at the bottom, and I think it's starting to be slightly overwhelming. I think there's value in keeping the UI simple.

Let's talk about this more tomorrow -- there seem to be a bunch of UI design choices here and in other issues and we should figure out a way to make these decisions in general.

**Comment by rabidbit** [comment]
I don't have a problem with having one button, as long as the button's label clearly indicates the action. I.e., if we keep the behavior of the current "Reset Code" button, then it should be renamed "Reset Question" and moved under the feedback window.

**Comment by seanlip** [comment]
Let's discuss this in person in more detail. While working on #278, I noticed that resetCode() resets the entire question, so if the student is on the second task, they will end up back at the first task with a clean slate. This is a bit drastic, especially if all they wanted to do was get the starter code for the second task. So I think the interaction design here might need a bit more thought.

**Comment by theresa-lee** [comment]
Fixed in #489
