### ISSUE TITLE
"Display error details" link hard to read in Dark theme

### ISSUE THREAD

**Issue by rabidbit** [google/tie#292]
"Display error details" link is legible in Light mode ...

![light](https://cloud.githubusercontent.com/assets/25493966/25826392/9423957c-33fb-11e7-9946-3a38630f0a4f.png)

... but not legible in Dark mode (should check legibility for both visited and unvisited link states) ...

![dark](https://cloud.githubusercontent.com/assets/25493966/25826395/964b277a-33fb-11e7-9e07-fb5efb465370.png)

**Comment by seanlip** [comment]
Hi @theresa-lee, would you be up for taking this one?

**Comment by theresa-lee** [comment]
I believe this was already fixed in #290 :)

**Comment by rabidbit** [comment]
Right, I think I was looking at the alternative UI which was not synced with master or merged into master at the time. Closing.
