### ISSUE TITLE
Persistent thinking dots when issue with parsing code

### ISSUE THREAD

**Issue by rabidbit** [google/tie#309]
Expected behavior: Floating dots (the dots UI that indicated that the application is "thinking" / "processing") do not display indefinitely.

Observed behavior: There are cases when the floating dots display indefinitely when there is an error in the user's code, even after "Reset Code" is pressed. This can prevent other feedback from displaying.

Steps to reproduce: Simple example is return ss in the first common char question.

High Priority: * This may be impacting user study results! *

**Comment by seanlip** [comment]
Looking at this, but having difficulty reproducing (Chrome on Mac). Do you mean just opening up the application and submitting `return "ss"`?

If you can reproduce locally, are there any console errors?

**Comment by rabidbit** [comment]
Return an undefined variable, not a string:
`return ss`

**Comment by seanlip** [comment]
I confirm this bug. Working on it.

**Comment by rabidbit** [comment]
Thanks seanlip!

**Comment by seanlip** [comment]
Fixed in #310
