### ISSUE TITLE
Indentation is often inconsistent and incorrect.

### ISSUE THREAD

**Issue by eyurko** [google/tie#31]
For some reason the editor is conflating tabs and spaces and it's causing all sorts of errors. I usually run into this on the i18n question when adding the length check to abbreviate.

Open app.html
Copy/paste solution.
Add lines to solution (hitting "Enter" after a complete line), and then tab inwards.
You see the correct indentation, but it's now mixed tabs with spaces.

**Comment by seanlip** [comment]
Can you give a repro case? E.g.

  1. Open app.html.
  2. Do stuff (...?)
  3. You see X, but Y should happen instead.

Otherwise it's going to be a bit hard to do anything with this...

**Comment by rabidbit** [comment]
I've seen this too. It seems like tabs are sometimes replaced with spaces. If you edit your code a bit (esp. add new lines, remove lines), you will probably experience this.

**Comment by rabidbit** [comment]
More specific steps to reproduce:
  1. Open page
  2. Delete existing code
  3. Type the following (where \t is a tab character):
```
blah
\tblah
\t\tblah
\t\tblah
\t\t\tblah
```

What it ends up becoming is:
```
blah
\tblah
    \tblah
        blah
        \tblah
```

Note the spaces (" ") in place of some tab characters.
