### ISSUE TITLE
Arrays as input are not currently supported.

### ISSUE THREAD

**Issue by eyurko** [google/tie#33]
For are_all_unique, it takes in an array as an argument, but that's not currently supported, so jsonVariableToPython crashes.

Launch app.html
Navigate to i18n question
Complete tasks up to first instance of filling in are_all_unique
App should crash.

**Comment by seanlip** [comment]
Could you please give repro steps, starting from "launch app.html"?

**Comment by eyurko** [comment]
Fixed in  #35.
