### ISSUE TITLE
Explicit styling for buttons

### ISSUE THREAD

**Issue by rabidbit** [google/tie#333]
With the exception of the "Run" button, the styling of button controls are not consistent when page is zoomed. We should probably use explicit styling to keep the control appearance consistent.

![screen shot 2017-06-15 at 10 25 13 am](https://user-images.githubusercontent.com/25493966/27193845-42536ef2-51b5-11e7-9d20-754c12087b88.png)

![screen shot 2017-06-15 at 10 25 27 am](https://user-images.githubusercontent.com/25493966/27193848-45bb8b4c-51b5-11e7-8114-ee4ae3bd6da1.png)

**Comment by dchen97** [comment]
Just checking but for this issue do we just want to address the "Reset Code" button or should we also style the dropdowns?

**Comment by rabidbit** [comment]
Both (explicit styling for all controls). The Run button is OK since it already has explicit styling.

**Comment by seanlip** [comment]
Fixed in #337. Thanks @dchen97!
