### ISSUE TITLE
Create Custom Modal Component

### ISSUE THREAD

**Issue by dchen97** [google/tie#334]
**Steps for Reproduction:** 
* Pull down `add-privacy-notice` branch (if not already merged into `master` branch).
* Open the `app.html` file in Chrome
* Click on link labeled `Privacy` in the bottom right corner.
* Notice that a pop-us is displayed with a "This page says..." title at the top.

The issue is that we don't want this title to appear, but since it's a browser-specific behavior, we need to make our own custom modals that can ideally be further extended to other use cases (i.e. Clippy pop ups).

**Comment by theresa-lee** [comment]
Done in #406
