### ISSUE TITLE
The prompt says "click the 'Next' button to move on" but the button says "Run".

### ISSUE THREAD

**Issue by eyurko** [google/tie#34]
Repro steps from scrach:

Start any question
Complete a task within that question
Prompt will have inconsistent message with button -- button should change, I think.

**Comment by rabidbit** [comment]
Yep. There should be no "Next" buttons (or any other button) to press to move on to the next **prompt**. When you are done with the whole **exercise** and its associated prompts, then there is a "Next" button.

**Comment by seanlip** [comment]
@rabidbit -- just to check, this is fixed, right?

**Comment by rabidbit** [comment]
Fixed in #61 .
