### ISSUE TITLE
Remove unicode feedback from Find Most Common Character question

### ISSUE THREAD

**Issue by rabidbit** [google/tie#342]
User studies show users get confused by the feedback regarding unicode. They assumed some action was required, spent time researching ways to resolve the comment, and either became frustrated when they realized they did not have to make any specific change to their code or became discouraged when they could not "resolve" the feedback.

**Comment by seanlip** [comment]
This should be fixed in #336, I think.

**Comment by seanlip** [comment]
Closing; this is fixed.
