### ISSUE TITLE
Add hinting system

### ISSUE THREAD

**Issue by rabidbit** [google/tie#344]
When user submits code multiple times but continue to fail unit tests, display a "would you like a hint?". Note this means not showing a hint button from the start (requiring the user to at least try a several times before offering a hint).

**Comment by seanlip** [comment]
Closing for now; will reopen if a specific need for this comes up in the future.

**Comment by rabidbit** [comment]
Re-opening and working on this.

**Comment by rabidbit** [comment]
Per user studies, users did not indicate a hinting system would significantly change their experience (some even raised issues on how it might be implemented). Closing.
