### ISSUE TITLE
Terms and Conditions page and link (for server version).

### ISSUE THREAD

**Issue by rabidbit** [google/tie#353]

**Comment by rabidbit** [comment]
(1) T&C static page needs to be created (see TIE team folder under Privacy and Legal) (2) the modal should link to the T&C page so that the user can open and view it at the time they read the modal content (3) add a link next to the Privacy link on lower right corner that links to the T&C page.

**Comment by rabidbit** [comment]
Setting to P2 for now, as we are focused on clearing client-version issues.

**Comment by seanlip** [comment]
Closing, not a client issue.
