### ISSUE TITLE
Code window flashes white when navigating between questions 

### ISSUE THREAD

**Issue by rabidbit** [google/tie#355]
Expected behavior: code window does not flash white for a split second when switching between questions.

Observed behavior: code window flashes white for a split second when switching between questions.

Steps to reproduce: navigate between questions and note code window flashes white for a split second.

**Comment by seanlip** [comment]
Closing -- per @theresa-lee's notes on #376:

1) planning not to be able to switch around questions like this for the updated UI 
2) Unless users complain about it, it isn't something I actually noticed that was a problem.
