### ISSUE TITLE
Prevent users from making calls to system-level classes.

### ISSUE THREAD

**Issue by eyurko** [google/tie#36]
Students should not be able to access AuxiliaryCode or System classes.

Repro steps (at least, the easiest ones):

Navigate to Problem 2
Paste in the following code:
`def isBalanced(s):
    return AuxiliaryCode.countNumberOfParentheses(s)
`
Run code. You should get an error message (rather than a SyntaxError or something) since it called one of the AuxiliaryCode methods. We should block students from calling any of those classes, potentially via throwing a SyntaxError or a ForbiddenNamespaceError of our own making. Something to tell them yo you can't run our code.

**Comment by krshubham** [comment]
One thing that I faced an issue while working for my project was :  "how to prevent a user from using system level tasks using functions like system() in c++ or exec() in js". Any hints?

**Comment by BenjaminHolland** [comment]
Seems like something that would be most easily done in the preprocessor. Add an underscore to make it more "pythonic" and then check to make sure those strings are never referenced in the user code, and throw an error if they are.
