### ISSUE TITLE
Show better error message if user deletes or modifies starter code.

### ISSUE THREAD

**Issue by eyurko** [google/tie#37]
Repro steps:

1. Open app.html
2. Navigate to the i18n problem.
3. Change "abbreviate" to "isBalanced"
4. Run code.
5. You should see this error: ["Your code threw an error: AttributeError: 'StudentCode' object has no attribute 'abbreviate' on line 42"]

It might be worth catching that error and saying something closer to "You seem to be missing an 'abbreviate' method. Check the starter code and make sure that it hasn't been deleted or modified accidentally."

**Comment by eyurko** [comment]
Another solid error message would be "You seem to have modified the starter code -- here it is again, if you need it:

{STARTER CODE}"

That way they can copy-paste it back in.

**Comment by seanlip** [comment]
Hm, this actually feels like an extension of the style tests we were considering. Maybe we should look into fleshing that out and implementing it.

**Comment by seanlip** [comment]
Fixed in #237, thanks @a-zakem! Closing.
