### ISSUE TITLE
Show reinforcement inputs in code font.

### ISSUE THREAD

**Issue by seanlip** [google/tie#370]
In the following screenshot, the last line reads `Fails on "lots of spaces"`. However, the input given here was actually meant to be "lots &nbsp;&nbsp;&nbsp;of&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spaces".

![screenshot from 2017-07-13 20 03 41](https://user-images.githubusercontent.com/10575562/28196588-88732078-6806-11e7-890a-343a1af1ac94.png)

The input should be shown in code font so that the space characters are visible.

**Comment by dchen97** [comment]
@seanlip Is this issue just trying to address the spaces not showing up in reinforcements or do we also want the inputs to be styled like the code in code snippets?

**Comment by seanlip** [comment]
It's really the former. I had the latter in mind only as a suggestion for
one possible way to address it.

**Comment by dchen97** [comment]
OK so something like this would work?
![image](https://user-images.githubusercontent.com/12034267/28386078-51262e1c-6c7f-11e7-995d-15fd2f146d25.png)

**Comment by seanlip** [comment]
Yep, I think so!
