### ISSUE TITLE
Reinforcement bullets might be overshadowing the targeted feedback

### ISSUE THREAD

**Issue by seanlip** [google/tie#374]
I've noticed, when playing through questions on TIE, that I sometimes miss the targeted feedback when the reinforcement bullets (the ones with ticks and crosses) appear. Perhaps this is because my eye is drawn automatically to the coloured things at the bottom.

![screenshot from 2017-07-17 15 08 20](https://user-images.githubusercontent.com/10575562/28291963-e983a902-6b01-11e7-9905-9927e93c4d06.png)

I wonder if there's a way to make the targeted feedback more prominent when it appears, or mute the reinforcement bullets a bit more, since IMO the former is more important? But it might be good to check first whether this phenomenon (of auto-skipping to the reinforcement bullets) is a more general one or if it is just me.

/cc @theresa-lee @rabidbit

**Comment by rabidbit** [comment]
Is this any better? ... 

![reorder-checkboxes](https://user-images.githubusercontent.com/25493966/28292267-254f9724-6b03-11e7-82c9-32339d423e87.png)

**Comment by seanlip** [comment]
Ooh -- yes, actually. After reading the bullets, I immediately go on to read the next thing.

**Comment by seanlip** [comment]
Closing this until we get more data to make a decision.
