### ISSUE TITLE
Whitespace does not render correctly in feedback window

### ISSUE THREAD

**Issue by rabidbit** [google/tie#38]
Expected behavior: When question or feedback looks at how whitespace is handled, whitespace is rendered properly in the feedback window.

Observed behavior: Whitespace appears as a single space character, regardless of whether it is a tab or consists of multiple whitespace characters.

Steps to reproduce:
1. Try reverse string exercise
2. Fail the whitespace prompt
3. Look at feedback

**Comment by rabidbit** [comment]
More specific steps to reproduce:
  1. Open page
  2. Delete existing code
  3. Type the following (where \t is a tab character):
blah
\tblah
\t\tblah
\t\tblah
\t\t\tblah

What it ends up becoming is:
blah
\tblah
    \tblah
        blah
        \tblah

Note the spaces (" ") in place of some tab characters.

**Comment by seanlip** [comment]
Fixing this is a bit tricky. I think it might involve displaying `code font` as part of the feedback paragraphs, so maybe we can try to support backticks or something (like github markdown).

(Btw, just for future reference, for this sort of thing it would generally be useful to include a screenshot showing the error.)

**Comment by seanlip** [comment]
Fixed in #70.
