### ISSUE TITLE
No feedback to user when parsing fails

### ISSUE THREAD

**Issue by rabidbit** [google/tie#40]
If you try the following in the reverse word question:
```
def reverseWords(word):
  if word == "moo cow bark dog":
    return "oom woc krab god"
```
Parsing fails and an error is written to console, but no feedback (or error) is given to the user.

Expected behavior: Some indication to user what went wrong.

Observed behavior: Nothing (unless you open a console and see the obscure error message written there)

**Comment by seanlip** [comment]
I checked, and the error lies in the _jsToHumanReadable function in FeedbackGeneratorService.js, where it does not handle null inputs. We should just fix this to correctly handle all possible types once and for all, I think.
