### ISSUE TITLE
User study - Not operator regex buggy

### ISSUE THREAD

**Issue by rabidbit** [google/tie#413]
Faulty regex for "Are you making sure to use the right NOT operator?"; specifically, it catches on `!"` in this code:
```
def check(char):
	if char == "!":
```
Also, awkward wording in "Are you making sure to use the right NOT operator?"

**Comment by seanlip** [comment]
@rabidbit -- what do you want the wording here to be?

**Comment by rabidbit** [comment]
"Are you using the right NOT operator?"

**Comment by seanlip** [comment]
Fixed in #431.
