### ISSUE TITLE
User study - Include line number in language detection

### ISSUE THREAD

**Issue by rabidbit** [google/tie#414]
When issue #413 occurred, it was very hard to know what part of the code was being referenced. Adding a line number to the feedback would help the user better understand where the problem is and also helps to better troubleshoot a potential bug.

**Comment by seanlip** [comment]
Hi @rabidbit -- here's what this currently looks like on the master branch:

![screenshot from 2018-01-10 13-45-02](https://user-images.githubusercontent.com/10575562/34797286-c857056c-f60c-11e7-9889-2d4bc7856e46.png)

Is the aim to get it to look like this? (See first dialog balloon in the screenshot below)

![screenshot from 2018-01-10 13-46-46](https://user-images.githubusercontent.com/10575562/34797301-d6c6f3b4-f60c-11e7-8dab-2480399dfc8d.png)

If not, please could you clarify any changes to the desired behaviour? Thanks!

**Comment by seanlip** [comment]
Btw, I thought about highlighting the lines in question, but one thing that's tricky about this is that some of the caught errors are not restricted to a single line -- e.g. do/while, switch, etc. So we need to figure out a UI for the multiline case too.

I'd suggest the UI from the previous comment, perhaps with the added text changed to "(See lines 2-3 of the code)", but let me know what you think!

**Comment by rabidbit** [comment]
Highlighting the line is the preferred way, as it's easier to find in a glance and is consistent with syntax errors. Can we just highlight the first line and let the user figure out the rest? This would already be a big help.

Also, this may be a chance for us to point to documentation on the library in question. One of the feedback we got from user testing is that there seems to be a lack of pointers to external documentation that could help. This need not be done in this PR, but in a future PR, if we point to the python comparison doc, for example (and this will be included in the python primer), I don't think we need to worry too much about highlighting all the lines that are relevant to the wrong language detection message. The user should be clever enough to fix this issue, as expected in real life. Highlighting the first line will help eliminate unnecessary scanning of the code, since we are not really testing the user on how python does comparisons.

**Comment by seanlip** [comment]
Hi @michaelrobbe, just to check, can we close this? (If so, please feel free to do that; I wasn't sure.)

**Comment by michaelrobbe** [comment]
Fixed in #557. Closing
