### ISSUE TITLE
OutputFunction isn't currently supported.

### ISSUE THREAD

**Issue by eyurko** [google/tie#42]
Any output function defined in the auxiliary code and then specified in the data schema (such as rle.js's decodeEncodedString) is not currently used.

Repro steps:

1. Go to the run-length encoding problem, once I've pushed my fixes.
2. Paste in the solution.
3. Run until you get to the "decode" step.
4. Your output should return 1x5xb for one correctness test, rather than 5xb, signifying that `AuxiliaryCode.decodeEncodedString` was not run on the output.

**Comment by seanlip** [comment]
Addressed in #48, I think.

**Comment by seanlip** [comment]
Fixed in #48. Closing.
