### ISSUE TITLE
User study - Support for regex

### ISSUE THREAD

**Issue by rabidbit** [google/tie#420]
If Skulpt supports it.

**Comment by seanlip** [comment]
I'm not actually sure what needs to be done here -- @rabidbit, please could you clarify?

I just tried writing:

```
import re

def reverseWords(s):
    match_object = re.match(r'(.*) are (.*?)*', 'roses are red')
    return 'olleH, nhoJ' if match_object else ''
 ```

and it seems to work...

**Comment by rabidbit** [comment]
Could have been related to importing issues. Closing.
