### ISSUE TITLE
User Study - Make Python Primer more readable

### ISSUE THREAD

**Issue by rabidbit** [google/tie#421]
Users seem to not be able to find content that is actually in the doc. (change fonts, etc.)

**Comment by seanlip** [comment]
I came across this during manual testing. I find the page rather hard to read/skim, and it has a lot of different colors that make it hard to figure out where to focus. There's also lots to absorb within a rather compressed format.

In thinking about the use case, I'm probably (as a user) trying to figure out how to do something in Python that I can't remember how to do. Perhaps it might be better to have a barebones list of common FAQs that I can skim?

**Comment by rabidbit** [comment]
Fixed in #499
