### ISSUE TITLE
Allow feedback to get to correctness stage

### ISSUE THREAD

**Issue by rabidbit** [google/tie#446]
When user cannot pass a test, feedback should eventually (after one or two failed user attempts) hand off to correctness test flow in order to allow user to display user code output. Examples:

![screen shot 2017-11-13 at 10 10 08 am](https://user-images.githubusercontent.com/25493966/32741453-21f6d9b0-c85b-11e7-98e3-e0fcae187854.png)

The above should hand off to correctness test flow, which will allow the user to display user code output (a subset of the correctness test feedback flow that skips the display of input and expected output and goes straight to allowing user to display user code output, in cases where the test case is SAMPLE_INPUT).

![screen shot 2017-11-13 at 10 16 26 am](https://user-images.githubusercontent.com/25493966/32741632-bce762c8-c85b-11e7-9c25-2be9a20841ee.png)

The above should also hand off to correctness test flow, which will follow the full correctness test feedback flow (display input to try, then displays expected output, then allows user to display user code output).

**Comment by seanlip** [comment]
This is a great catch, thanks @rabidbit. Couple of questions:

(a) What is the exact trigger for handoff -- same feedback is shown consecutively 2 times? 
(b) What sorts of feedback does this apply to? I'm guessing it's only buggy output and suite-level tests (and not about runtime errors, syntax errors, prereq checks, etc.)?

**Comment by rabidbit** [comment]
(a) when there is no other new feedback to give, the correctness test feedback is the final fallback. There should be no more than 2 consecutive occurrence of the same feedback. I actually think even limiting it to just one occurrence is fine, but I don't have very strong feelings about this, as long as it's not > 2.
(b) Correct, the exceptions would be things like syntax or runtime errors. I do not anticipate it will be a bad user experience if the same syntax error is repeated until the user figures out what's wrong.

**Comment by seanlip** [comment]
This should now be fixed with the new feedback flow implementation.
