### ISSUE TITLE
Change "Try addressing the error before you run again." to feedback rather than error

### ISSUE THREAD

**Issue by eyurko** [google/tie#473]
Repro steps:

Start question.
Change "return ''" to "return s"
Click "I think I'm done"
Click "I think I'm done"

Given that you're getting KNOWN_BUG feedback, it seems more apt to suggest "Try addressing the feedback before you run again" rather than "Try addressing the error". It's an error, sure, but it's not phrased as such in the conversational UI.

**Comment by rabidbit** [comment]
IIUC, I think this supposed to be addressed in the PR #472 , which is not finished yet.

**Comment by rabidbit** [comment]
Actually, I think this can be covered by issue #446 Closing. Please feel free to re-open if you think this is not covered by #446 .
