### ISSUE TITLE
"Check My Code" Button does nothing and that stresses me out

### ISSUE THREAD

**Issue by eyurko** [google/tie#474]
So I talked to John and it sounds like it's a placeholder for a currently unimplemented feature.

I'm in favor of removing it until at least that feature is implemented, because right now it's two different pathways to the same endpoint and that's very confusing for me, as a rando.

I briefly proposed changing it to "How am I doing?" but that builds in an antipattern for interviewing as we can't provide feedback to candidates on their performance. Check my code, by the same logic, might also not be good.

**Comment by rabidbit** [comment]
I agree with removing that second button until we have a clear and distinct function it serves. "I think I'm done" IMHO has softened the tone from the old "Submit" label; so, maybe we don't need the seconds button.
