### ISSUE TITLE
When switching from light to dark mode and vice versa, the feedback balloon colors take time to update.

### ISSUE THREAD

**Issue by seanlip** [google/tie#475]
Steps to repro:
1. Submit an answer.
2. Change from light to dark mode, and then back again.

You'll see that the feedback balloon colors do not change instantly. After a while, they slowly fade to the correct color.

**Comment by rabidbit** [comment]
I think this is on non-Mac OS systems. Added screenshot to #480 (created that before seeing this one). Closing this one and will pick up #480.
