### ISSUE TITLE
The code balloons in the feedback take up a lot of space.

### ISSUE THREAD

**Issue by seanlip** [google/tie#477]
I noticed that the code balloons in the feedback list take up lots of vertical space, and there's a lot of whitespace between the second line of code and the "View full code" link.

Given that the learner is presumably more interested in reading the feedback than their own responses (which are mainly for reference), perhaps we could make the font/margins/line-spacing for those balloons a bit smaller?

![screenshot from 2017-12-28 20-11-37](https://user-images.githubusercontent.com/10575562/34429309-612ced58-ec0b-11e7-819f-9c4a39596b02.png)

**Comment by rabidbit** [comment]
Note that empty spaces (containing only new line characters) are rendered. In fact, the template code for this question has an empty line, which is reflected in the user's speech bubble if they submit without editing the code.

**Comment by rabidbit** [comment]
Fixed in #498
