### ISSUE TITLE
"The code doesn't seem to work" text might be misleading?

### ISSUE THREAD

**Issue by theresa-lee** [google/tie#491]
This might just be me, but in the feedback (like say after doing a reset and just running the starter code), saying the code doesn't seem to work can be misinterpreted as the code not compiling/running correctly? The code might not complete what the prompt is asking for but technically... it's working? Maybe just a bit more clarification, like the code isn't working as intended or something?

**Comment by seanlip** [comment]
I agree -- good catch, thanks! Fixed in #491, PTAL.
