### ISSUE TITLE
Correct state is not stored and does not survive page reload

### ISSUE THREAD

**Issue by rabidbit** [google/tie#505]
Reproduce:
1. Solve question
2. Reload page
Expected: congratulatory feedback is given
Observed: last known failure feedback is given

This may confuse the user into thinking the code in the coding window is incorrect.

**Comment by rabidbit** [comment]
This was largely addressed in #509. In testing it, it seems a user could edit the code before reload, then the feedback and code will still not be in sync.

Suggest in a separate PR that we display the last user code submit before the last feedback. This would provide the user context for the feedback, even if the feedback no longer applies to the current code.

**Comment by theresa-lee** [comment]
Sounds good, I created a new issue #510
