### ISSUE TITLE
Syntax error refers to splice (which does not apply Python)

### ISSUE THREAD

**Issue by rabidbit** [google/tie#537]
One of the syntax error messages refers to splice method (which does not apply Python). This confuses users and wastes their time as they try to research why this should be used and how.

**Comment by seanlip** [comment]
Wait -- we still need to fix the primer, right?

**Comment by eyurko** [comment]
Sorry, you're right, yes.

--
Eric Yurko

**Comment by rabidbit** [comment]
Added slice and splice sections with #539

**Comment by seanlip** [comment]
Fixed in #539, thanks @rabidbit!
