### ISSUE TITLE
processSolutionAsync test fails randomly

### ISSUE THREAD

**Issue by rabidbit** [google/tie#544]
There seems to be some flakiness in the processSolutionAsync tests. Different parts of the test set fails randomly (sometimes no failure, sometimes fails, sometimes fails on different tests, sometimes fails with different failure messages).

To reproduce, run tests locally. Sometimes processSolutionAsync test will fail, sometimes it will pass. The same is observed when submitting commits to GitHub and running tests through Travis.

**Comment by seanlip** [comment]
Fixed in #547, I think.
