### ISSUE TITLE
TIE not opening on Windows machines

### ISSUE THREAD

**Issue by rabidbit** [google/tie#545]
Users with Windows machines report seeing a "Chrome HTML file" description of question.html, and opening the file using Chrome or MS Edge results in a blank screen.

I've ordered a temporary Windows machine to do testing on.

**Comment by SetCodesToFire** [comment]
I am using a windows machine and I didn't face any problem opening the file.

**Comment by seanlip** [comment]
Thanks @SetCodesToFire! This has been fixed, I think -- we just forgot to close it. Doing so now.

Thanks for letting us know!
