### ISSUE TITLE
Recursive Loop check only works for Skulpt errors.

### ISSUE THREAD

**Issue by eyurko** [google/tie#564]
https://github.com/google/tie/blob/cbf833dcffc864d4771e7c8438b4337cce0b045f/client/question/services/FeedbackGeneratorService.js#L598

This line should have some form of "|| errorString.contains('maximum recursion depth exceeded').

The exact error is: RuntimeError: maximum recursion depth exceeded while calling a Python object on line 2, which is technically a runtime error.

**Comment by rabidbit** [comment]
Is this issue still open or was it fixed in #566 ?
