### ISSUE TITLE
Remove the extra characters that appear at the end of stdout.

### ISSUE THREAD

**Issue by kchen05** [google/tie#597]
After running user code, the stout returned contains the stdout (and string separators) for all of the test cases that were executed (all test cases up until and including those of the current task or all test cases up until an error occurred, whichever comes first). While it contains all the necessary information, the returned stdout also has a decent number of random extra characters at the end.

This issue occurs on both the server and client version, but it seems that the extra characters are random as they will differ between runs.

**Comment by kchen05** [comment]
The extra characters that appear at the end are resulting from the performanceTests. When a given question has performance tests, the stdout resulting from these runs is then added to the end of the overall stdout array. This means that when we are standardizing the output array, we are essentially splitting the stdout of the correctness tests from the stdout of the performance tests. Given the new understanding, I think that the implemented approach of standardizing the stdout is still the best method since it is the cleanest way to process the stdout and allows room for later adding functionality to display tests that failed performance tests rather than correctness tests. @seanlip @eyurko Thoughts on this approach versus a different one perhaps? I can also add some comments to better explain the reasoning behind standardizing the output array.

**Comment by eyurko** [comment]
That seems reasonable. Fine with it.

Good investigation, Kelly!
