### ISSUE TITLE
The video at https://google.github.io/tie/ fails to autoplay when the page is loaded.

### ISSUE THREAD

**Issue by seanlip** [google/tie#637]
It used to be the case that the video at https://google.github.io/tie/ would autoplay when the page is loaded. The video would show a demo of what the TIE user experience looks like.

However, now it does not, so it looks like a static image. This might be due to a Chrome update, possibly this one: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by rabidbit** [comment]
Added controls attribute to display controls, since Chrome no longer auto-play videos.

**Comment by seanlip** [comment]
Confirming this is fixed. Thanks!
