### ISSUE TITLE
[UI problem] GUI problem

### ISSUE THREAD

**Issue by huynhducloi** [google/tie#81]
On the GUI it said "You'll see the first question to your right". However, the question appears in the bottom.

**Comment by seanlip** [comment]
Thanks, @huynhducloi. Would you mind providing repro insructions (from scratch), expected/observed behavior, and a screenshot, similar to #83?

**Comment by huynhducloi** [comment]
Repro step:
1. Download the package
1. Run app.html
1. The original windows look like this
![image](https://cloud.githubusercontent.com/assets/3073672/24631824/a66fd146-1876-11e7-97ce-6ceabd2ec5bf.png)


***The question windows is supposed to be positioned to the right, however it is at the bottom***

**Comment by shaman-rajan** [comment]
Addition to the repro step: This depends on the size of the browser. If the size is too small, the question doesn't fit on the right it is moved below the editing area.

**Comment by seanlip** [comment]
Why was this closed?

**Comment by seanlip** [comment]
Closing. Chatted with @rabidbit and decided that question windows should not reposition themselves when browser viewport is resized. Will file a new issue to fix this.
