### ISSUE TITLE
[UI Issues] Output text cannot wrap within the text area

### ISSUE THREAD

**Issue by xiaoyig** [google/tie#84]
The output screen at the left top corner has a black box to indicate the Run results, which only scales based on the screen size instead of the text length. Thus, if the text within this black box is longer than screen size, the rest text will simply extend out of the black box, which is not very elegant. 

Repro instructions:
1. Run app.html
2. Navigate to Question-1
3. Change code to return a very long string, such as
<img width="674" alt="screen shot 2017-04-03 at 1 40 57 pm" src="https://cloud.githubusercontent.com/assets/14989337/24630894/374ca652-1873-11e7-8a7d-220de99b2957.png">

4. Click on Run button
5. Actual result will come out in this black box 
<img width="664" alt="screen shot 2017-04-03 at 1 36 29 pm" src="https://cloud.githubusercontent.com/assets/14989337/24630929/5b647b46-1873-11e7-8c06-f0c7081b3591.png">

We can find out the output text exceeds the actual size of the black box.

**Comment by seanlip** [comment]
Thanks! Please could you provide repro insructions and a screenshot?

**Comment by huynhducloi** [comment]
Another problem with the output screen is that it cannot provide the output from internal of the function. For example, if we do something like this:
```python
def encoder(word):
   print 'a'
   return word
```
and 'a' will not be printed.

**Comment by seanlip** [comment]
@huynhducloi would you mind filing this as a separate issue, please? Easier to keep track that way. Thanks!

**Comment by xiaoyig** [comment]
Issue fixed by @lk-chen and me

<img width="671" alt="screen shot 2017-04-05 at 5 11 57 pm" src="https://cloud.githubusercontent.com/assets/14989337/24732043/0b3731d4-1a23-11e7-8ee2-40d9d1115cd8.png">

**Comment by eyurko** [comment]
Fixed by #151
