### ISSUE TITLE
Question 2 (parenthesis): hints not matching the real problem of user's code

### ISSUE THREAD

**Issue by skywalker-lili** [google/tie#85]
In the code, we just return Booleans such as `False,` `False or False`, `False or False or False`...and so on. However, the hints got different every time. Seems like the hints are just iterating in the back-ends regardless of the actual mistake of user's code.

And if we return anything but an expression that results in `False`, such as `None`, `True`...It displays the input, output and the expected output. I kind wish it always displays so that users know what input they are tested against.

**Comment by seanlip** [comment]
Thanks for filing, @skywalker-lili! This looks like an important bug, but there isn't enough detail to reproduce it.

Would you mind providing clear reproduction instructions, expected/observed behavior, and a screenshot, similar to #83?

**Comment by skywalker-lili** [comment]
Sure. Here is how to reproduce it:
1. Open "app.html"  
  
2. Navigate to "Question 2: Balanced Parentheses"  
  
3. Modify the `isBalanced(s)` function to return `False`. Click "run" button to get a hint.
![hint1](https://cloud.githubusercontent.com/assets/5773915/24670729/0fddaaa6-1924-11e7-987c-36cea6e5daf5.png)
  
4. Then modify the `isBalanced(s)` function to return `False or False`. Click "run" button to get a hint.  
![hint2](https://cloud.githubusercontent.com/assets/5773915/24670782/498a25ea-1924-11e7-9f53-a3fd4ab35a23.png)  
  
5. Then modify the `isBalanced(s)` function to  return `False or False or False`. Click "run" button to get a new hint.
![hint3](https://cloud.githubusercontent.com/assets/5773915/24670791/52f51630-1924-11e7-91f2-86825844f2f0.png)  
  
6. The hints from step 3-5 are different even though the code made the same mistakes by just returning `False`. The last hint is especially misleading by assuming user's code is counting number of parenthesis.

Expected behavior: hints should be stable when user's code made same mistakes or when making the same wrongs in test cases. Also, hints shouldn't mislead the user what kind of mistake its code has.

**Comment by seanlip** [comment]
@skywalker-lili, thanks for adding the detail!

**Comment by andersonw** [comment]
Just wanted to say that this behavior seems intended: if you provide multiple hints for the same buggyOutputTest, then it'll just iterate through all of them as long as the code is edited in some way but returns the same result. So this feels like two separate issues:

1) The criteria for when to give the next hint should be stricter than just "the code isn't exactly the same". Maybe some sort of edit distance or timestamp check?

2) The "countNumberOfParentheses" function isn't doing the intended thing; I think the "return numLeft == numRight" line should be outside the for loop.

**Comment by andersonw** [comment]
I'll add myself to fix 2 (removing the tab does indeed fix the issue in this case), but should 1 be moved to a separate issue? @seanlip

**Comment by seanlip** [comment]
Yes, let's move 1 to a separate issue. Thanks @andersonw!

**Comment by seanlip** [comment]
Second part fixed in #212; first part filed as #211. Thanks @andersonw!
