### ISSUE TITLE
Description of question 4:Run-Length Encoding

### ISSUE THREAD

**Issue by jujudydy8196** [google/tie#89]
In the description of question 4:
![image](https://cloud.githubusercontent.com/assets/7587606/24636743/332a99e4-1891-11e7-957f-e5221352e0b9.png)

"abcccccd" should be encoded as "ab5xcd" but not "ab5xc"

**Comment by eyurko** [comment]
Good catch! Mind submitting a PR to fix it? It'll be good practice.

**Comment by seanlip** [comment]
Fixed in #110. Thanks @xiaoyig!
