### ISSUE TITLE
No auto indentation for Python

### ISSUE THREAD

**Issue by Eumenides2009** [google/tie#90]
Hi,

The current version of TIE does not do auto-indentation when there is a new line after 'def', 'if' or 'where' clauses. It just aligns the new line with the previous one. It may be more user-friendly and save some time if this feature is included, since it is not convenient for users to count spaces themselves.

I captured two screenshots to compare between TIE and Leetcode.

![screen shot 2017-04-03 at 6 31 24 pm](https://cloud.githubusercontent.com/assets/14260930/24638265/eda11898-189b-11e7-8721-0c0097d9f1f6.png)
![screen shot 2017-04-03 at 6 32 25 pm](https://cloud.githubusercontent.com/assets/14260930/24638264/ed9fa0b2-189b-11e7-9035-1d2ff08feafc.png)

**Comment by luofei11** [comment]
Working on this issue...

**Comment by eyurko** [comment]
Fixed by #103.
