### ISSUE TITLE
Question 1 default name for function parameter confusing

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#91]
![screen shot 2017-04-03 at 7 36 24 pm](https://cloud.githubusercontent.com/assets/1597618/24639675/2e531fee-18a6-11e7-88d8-2625598263ca.png)

The default parameter here is called "word", which is confusing because the function expects a sentence.

Repro steps:
1. Open app.html on a browser (chrome used in above screenshot)

**Comment by eyurko** [comment]
I wouldn't necessarily say that it's a sentence, but it seems valid to change the starter code parameter to s, str, or something similar. Would you mind submitting a PR to fix it?

**Comment by eyurko** [comment]
Fixed by #106.
