### ISSUE TITLE
Strange text when undo is used in editor

### ISSUE THREAD

**Issue by shaman-rajan** [google/tie#92]
Pressing undo in the editor from the default text makes strange text appear in the editor.

![screen shot 2017-04-03 at 7 52 46 pm](https://cloud.githubusercontent.com/assets/1597618/24639806/2732e388-18a7-11e7-92aa-0f0836504c1b.png)

Repro steps:
1. Open app.html
2. Click on editor and press undo (command-Z used here on a mac)

**Comment by seanlip** [comment]
Fixed in #143. Thanks @shaman-rajan!
