### ISSUE TITLE
Confusing result when outputFunctionName != null 

### ISSUE THREAD

**Issue by Jiaqhimh** [google/tie#95]
Retro steps:
In step3 of Question 4, Run-Length Encoding: 
We write a one-line program to return the input directly, then click 'run'.
<img width="1295" alt="screen shot 2017-04-03 at 7 04 53 pm" src="https://cloud.githubusercontent.com/assets/14021116/24643515/4e1df732-18c3-11e7-983f-61fd80e284d8.png">

Output:
The output of our function will be 'bbbbb' when input is '5xb'. 

Expected behavior:
The output of our function will be '5xb' when input is '5xb'.

Possible causes:
'bbbbb' is the result after using the function 'AuxiliaryCode.decodeEncodedString' defined in 'outputFunctionName' attribute in JS script of questions on our output '5xb'. It may confuse some users cause the output in the console is not the actual output of their function. 

Suggestion:
Maybe we can modify the text when outputFunctionName != null. For this question, a possible output could be 'Output after decoding:', 'Expected Output after decoding'. Or we can modify the question: give them the decoding function/strategy to ask them write correct encoding function to make sure the string remain the same after encoding and decoding. Or in the last step we can ask them to implement the decoding function by themselves.

**Comment by eyurko** [comment]
What would you suggest?

**Comment by seanlip** [comment]
@eyurko -- isn't there already a suggestion in the issue?
