### ISSUE TITLE
[Question Schema] No Checks on Previous Tasks

### ISSUE THREAD

**Issue by xchenan** [google/tie#96]
The Judge does not test my code for tasks that I've passed before. 

For example, on Question 2, my code went through Task One smoothly but had bugs on Task Two. Then I made some changes so as to pass the tests for Task Two. Even through now my code failed on the tests of Task One, the Online Judge would not find out, but instead moved me forward to the third task. Such design seemed quite inappropriate to me, because the next round task, based on the previous one, encourages challengers to generalize their codes, rather than allowing them to pass the tasks individually.

**Comment by eyurko** [comment]
Thanks -- could you provide repro steps from a clean copy and a screenshot of the error in progress? We're aware of this issue and working to address it, but it's good to have it captured in the tracker.

**Comment by xchenan** [comment]
Repo steps:

1. Open "app.html".

2. Navigate to Question 2, which has three tasks in total.

3. Do code as follows then click "Run", which passes all tests for Task One:
![image](https://cloud.githubusercontent.com/assets/6829866/24670444/e3185062-1922-11e7-930a-44a1f9781fe3.png)

4. The Judge now leads me to the second task.
![image](https://cloud.githubusercontent.com/assets/6829866/24670519/3908e036-1923-11e7-870e-4a63c4af5c85.png)

5. Likewise, do code as follows then click "Run", which should pass Task Two but not Task One:
![image](https://cloud.githubusercontent.com/assets/6829866/24670592/7eee1a4e-1923-11e7-9ee9-aaa2d00c997c.png)

6. However, the Judge still leads to the next task, instead of reporting test failures on Task One:
![image](https://cloud.githubusercontent.com/assets/6829866/24670638/aed1bcac-1923-11e7-99fa-102713e85fab.png)

Expected behavior:
The Judge shall report test failure on tests of all current and previous tasks, instead of merely the current.

**Comment by seanlip** [comment]
Fixed in #173. Thanks!
