### ISSUE TITLE
Unable to create custom test cases in the webpage

### ISSUE THREAD

**Issue by eprym** [google/tie#99]
Sometimes users want to create custom test cases to figure out the bugs in their codes, but there is no place to do it in the webpage right now. So it should be helpful to have it and maybe it's better to embed a default right algorithm for each problem to show the correct result for the custom test case.

**Comment by eyurko** [comment]
Please make sure you're following our format for filing issues -- you'll want to have clear reproduction steps, screenshots and expected/observed behavior.

What do you mean by "embed a default right algorithm"? And how would you go about supporting custom test cases?

**Comment by eprym** [comment]
Here is a screenshot from leetcode which shows the feature that I want.

![screenshot from 2017-04-04 11 02 20](https://cloud.githubusercontent.com/assets/7578062/24671452/65aca2be-1926-11e7-829f-9a3c6ead67d3.png)


By default right algorithm, I mean problem creator should provide the right algorithm to produce the expected result. So users will get the correct result for the custom test cases that they create.

**Comment by seanlip** [comment]
In an interview setting, you don't really get the chance to do this, at least as stated here. So this might need a bit of refinement, given the context of this tool.

Would an equivalent idea be for the student to "ask the interviewer to clarify what the output should be for test case XXX?" Is this something that happens in practice?

**Comment by seanlip** [comment]
Discussed in team meeting. Decided not to do this, because it's not something that generally happens in the real-world analogue.
